### ISSUE TITLE
Implement Sonification 

### ISSUE THREAD

**Issue by Rek3650** [RITAccess/data-analyzer#1]
Implement a level of controlling graph data by continually shrinking the size of the cursor. Cursor will be used to read out sonified data.

Look at Ethan's comment bellow.

**Comment by 7imbrook** [comment]
:+1:

**Comment by ethanjurman** [comment]
![sonfication_maybe](https://cloud.githubusercontent.com/assets/1131494/6196087/f9cf9fdc-b3a2-11e4-8e82-7adee2a2ea88.png)

**Comment by 7imbrook** [comment]
:+1:
