### ISSUE TITLE
Delete Row/Col does not work

### ISSUE THREAD

**Issue by smcintosh881** [RITAccess/data-analyzer#102]
Rows and Cols will not remove from the table in firefox and safari.

**Comment by melissay94** [comment]
There is a function being called in javascript that isn't recognized in these two browsers which is .includes. As such a new way will have be implemented that will help it work in all browsers.

**Comment by melissay94** [comment]
Changed .includes to .substring that checks for if the substring of the cell matches the necessary criteria and all the browsers tested on the Macs now allows for the proper deletion of columns and rows.
