### ISSUE TITLE
Nothing Read or Read Twice (VoiceOver)

### ISSUE THREAD

**Issue by baozi90** [RITAccess/data-analyzer#103]
When using VoiceOver to read the Load CSV and Create New Table buttons, VO-A and VO-L  (plus UP and DOWN arrows) reads over the actual Load CSV button and then reads the "Load CSV" text again, and the same goes with the Create New Table button. This occur on Safari and Chrome. On the other hand, nothing is read out when using either VO-A nor VO-L keys on Firefox.

Additionally, tab works on all browsers: Firefox, Chrome, and Safari (majority of the time). 

I'm thinking of making either the actual buttons or the text itself not readable, but that might have to come in after making sure the ones on Firefox works at least once.

**Comment by smcintosh881** [comment]
Another slight issue I'm not sure how to fix is that VoiceOver works differently for each browser.

**Comment by smcintosh881** [comment]
I think the main issue we are going to have is that each browser (Chrome, FireFox, Safari) all interact differently with voice over. Another factor is your current software version. 
I did some changes so that in Chrome and Safari when using VO + arrow keys the Load CSV and New Table buttons only go over once. I'm not sure how to get FireFox to work with this command. FireFox also seems to read differently. It seems to repeat a lot.

**Comment by baozi90** [comment]
What Shannon mentioned might relate to issue #111.

**Comment by smcintosh881** [comment]
After a great deal of research, I do not believe that this issue can be resolved. Each version of OS comes with a different version of VoiceOver. When the same browser is tested on Mavericks, Yosemite, El Capitan, all three read the same elements differently. Another obstacle other than OS inconsistencies is different browsers. The main three, Chrome, Safari, FireFox all read differently. Chrome and Safari are most similar, however still vary. I tested a well known/popular website such as MSN or YellowPages, and VoiceOver reacted differently for each. 

At this point Chrome and Safari run the application most optimally with VoiceOver. All three occasionally repeat the same element multiple times, however all elements are read at least once which is more important.
