### ISSUE TITLE
Reset Button For Text Color

### ISSUE THREAD

**Issue by baozi90** [RITAccess/data-analyzer#107]
Since the reset button for the site background color also resets the text and the border, the reset button for the text color should also reset the site background color as well.

On the other hand, I think it would be better if the site background color reset button resets only the background color and the reset button for the text resets both the borders and the text color.

**Comment by jmiller656** [comment]
The reset background color resets the text if high contrast is checked. Otherwise, it does just the background and the border. I think it makes sense to keep it this way so that we can be guaranteed that the border is always contrasting with the background.

**Comment by baozi90** [comment]
Then I guess the other option would be add reset the site background to the text reset button when the high contrast is  checked.

**Comment by baozi90** [comment]
Along with the text color change, what if it also changes the text of the graph?

**Comment by jmiller656** [comment]
I think it would be better to keep the graph text color changing only with the graph color so we can guarantee that it is contrasting and also so we can minimize the number of times the graph is redrawn, because that slows things down a bit.

**Comment by baozi90** [comment]
Okay, sounds good.

**Comment by baozi90** [comment]
Same as another issue.
