### ISSUE TITLE
Scatter Plot sleep study error

### ISSUE THREAD

**Issue by jmiller656** [RITAccess/data-analyzer#109]
When you try to make a scatter plot using sleepstudy.csv, it shows up blank. I could be wrong, but I think this relates to the numerical data labels and how they start at 18.

**Comment by erl7902** [comment]
That shouldn't be the problem; I have it set to dynamically create the labels. Could be some of the leftover code from when I was testing earlier

**Comment by erl7902** [comment]
Fixed in part - added parseFloat when calculating min and max values. Unfortunately there's now an issue with drawing - will be working on that

![anexample](https://cloud.githubusercontent.com/assets/9061088/8677895/af9049b4-2a1f-11e5-89da-511fd2f00dd6.png)
