### ISSUE TITLE
github pages cannot run application

### ISSUE THREAD

**Issue by ethanjurman** [RITAccess/data-analyzer#11]
http://ritaccess.github.io/data-analyzer/
it doesn't load the correct resources to execute the javascript.

**Comment by 7imbrook** [comment]
This may be due to the recent pages outage today.

**Comment by ethanjurman** [comment]
From what I can tell it cannot load the javascript files in the different folders.

**Comment by ethanjurman** [comment]
found out that when testing it locally, javascript files linked in html are not case sensitive. When served in gh-pages, they are case sensitive (`../libs/require/require.js` should have been `../libs/require/Require.js`). it should be working correctly now.
