### ISSUE TITLE
VoiceOver Pop-Up Window for Load CSV

### ISSUE THREAD

**Issue by baozi90** [RITAccess/data-analyzer#111]
When using VO-A for VoiceOver: after Load CSV pop-up window "closes", VoiceOver starts reading: 

[Safari]
<img width="674" alt="messages image 1843479682" src="https://cloud.githubusercontent.com/assets/11864006/8603208/cee89bce-2644-11e5-9c91-a12c1bc4825f.png">

Then it continues to the h3 tag for "Change Background Color".

In this case, VoiceOver should start reading from the beginning of the site, where the site title is, instead of reading the input text and the text next to the input first.

**Comment by baozi90** [comment]
Additional note: For Chrome and Firefox, it does seem read out something from the pop-up but then it goes back to the site title.

**Comment by smcintosh881** [comment]
I think I fixed what you were describing. Can you try testing it on your computer? El Capitan's VoiceOver works slightly differently than Yosemite.

**Comment by baozi90** [comment]
Yup, it still reads "Line Graph..." on the pop up and skips to the "Change Background Color" section on Safari. Same for Chrome and Firefox, still reads "dimmed, button" then (may have to wait for around 2 to 8 seconds) start reading rom the site title.

**Comment by smcintosh881** [comment]
I think this problem is going to be almost impossible to fix because each software version and browsers seems to read it differently. Safari and Chrome are similar but not exactly the same and FireFox is kind of unpredictable.

**Comment by smcintosh881** [comment]
I don't believe this can be fixed. This bug cannot be recreated. I think its an issue with the interaction between voiceover version and the browsers type/version
