### ISSUE TITLE
Caution Message When Line Color May Not Be Visible On Graph

### ISSUE THREAD

**Issue by baozi90** [RITAccess/data-analyzer#112]
When user changed the line color to the same/not as visible color as/when on the background color of the graph, there can be a caution message of some sort, such as making the border of the text input for changing either of the colors red. Along with that, the message can be "current line color choice may not be visible with the current graph background color".

Example of black line on black background:

[Before]
<img width="303" alt="screen shot 2015-07-09 at 14 32 59" src="https://cloud.githubusercontent.com/assets/11864006/8603745/2859f222-2648-11e5-9afa-57beb2bf0426.png">

[After]
<img width="327" alt="screen shot 2015-07-09 at 14 33 16" src="https://cloud.githubusercontent.com/assets/11864006/8603750/32a7b43a-2648-11e5-90ef-c9a7cecccafd.png">

**Comment by baozi90** [comment]
Instead of a pop up, maybe something like these might work better:

[1]
<img width="993" alt="screen shot 2015-07-13 at 09 21 43" src="https://cloud.githubusercontent.com/assets/11864006/8650429/c01b7298-2940-11e5-97e1-691e56125ff2.png">

[2]
<img width="483" alt="screen shot 2015-07-13 at 09 22 02" src="https://cloud.githubusercontent.com/assets/11864006/8650434/cfcfe61a-2940-11e5-8490-690412300202.png">

Also, same for the line color change, additional warning for the graph background change can be added as well.

**Comment by smcintosh881** [comment]
How does that work with VoiceOver?

**Comment by jmiller656** [comment]
I agree that both of the options above are much more favorable and user friendly than a popup, but if we were to use them, I think it would be difficult to force the voiceover to read it/not read it repetitively.

**Comment by smcintosh881** [comment]
We could have it focus to the warning, but then the user would have to navigate all the way back to the color change section which could be cumbersome.

**Comment by baozi90** [comment]
On the other hand, does it still count as accessible if the user can use VO-A or more of VO-L arrow keys?

Example:
<img width="988" alt="screen shot 2015-07-13 at 09 41 34" src="https://cloud.githubusercontent.com/assets/11864006/8650849/935a0dd4-2943-11e5-8139-3c9d4da2adf0.png">

**Comment by smcintosh881** [comment]
I think that is the warning near the color change section it would be easier to return to. It also adds more to the screen which I'm not sure how that will fit in

**Comment by baozi90** [comment]
We could also key this kind of warning there, just to have it there and key the pop up for the first warning.

**Comment by baozi90** [comment]
Or we could just have the triangular exclamation mark and try to make it accessible. 

[reference]
<img width="459" alt="screen shot 2015-07-13 at 09 49 47" src="https://cloud.githubusercontent.com/assets/11864006/8651026/9bfedd2e-2944-11e5-81b9-c5142816b97b.png">

**Comment by smcintosh881** [comment]
I think the triangle is cool. This could be useful

http://fortawesome.github.io/Font-Awesome/icon/exclamation-triangle/

**Comment by jmiller656** [comment]
![warning](https://cloud.githubusercontent.com/assets/8846806/8652108/dcc188c4-294a-11e5-9d02-aa3868639911.png)
How does this look?

**Comment by baozi90** [comment]
Looks good :)

**Comment by smcintosh881** [comment]
I added aria labels and a little bit of padding onto the triangle warnings.

**Comment by jmiller656** [comment]
Ok, so I've kept the triangle warnings and brought back the popup warnings. We need something that takes the focus for the screen reader to read it in order for this to be accessible. We could focus on the warnings and then return focus, but that might be a bit too excessive when the popups do the job and will probably cause less problems between browsers/screen readers.

**Comment by smcintosh881** [comment]
I think the pop up works best with a return focus to the input box. I don't think we need the triangle

**Comment by jmiller656** [comment]
The triangles will be good to keep in order to account for which lines may be lacking an acceptable amount of contrast. Since we have this and the popups which are accessible, I will close this issue.

**Comment by baozi90** [comment]
I noticed there isn't a triangle for the graph background color, should we add one for that as well?

**Comment by jmiller656** [comment]
If the graph background color changes to something that makes some of the lines lack visibility, the line(s) that lack visibility get a triangle warning. I think that is sufficient.

**Comment by baozi90** [comment]
Adding to my comment:

What we have: when changing background color that trickers a pop up warning, triangle warning shows up next to the corresponding line color change input.

When changing color in the line section, no triangle show up next to neither the line or the graph background corresponding input section. For this, 
- either a triangle shows up next to the input for line only, 
- or next to both the line and graph background.

**Comment by baozi90** [comment]
Another thing, I'm not sure if it's related to the warnings, but when I tried to change a line color such as black when the graph background is already changed to black, the line color doesn't change and I've got this error as a result:

<img width="1280" alt="screen shot 2015-07-13 at 14 53 05" src="https://cloud.githubusercontent.com/assets/11864006/8658022/53760868-296f-11e5-995e-5e1a10c5fcf1.png">
