### ISSUE TITLE
Malfunction Color Change

### ISSUE THREAD

**Issue by baozi90** [RITAccess/data-analyzer#114]
I'm not sure what this is but it's definitely something:

<img width="739" alt="da" src="https://cloud.githubusercontent.com/assets/11864006/8621076/8dfdaa8e-26f1-11e5-8883-f94aa85e9e55.png">

This is what I did:
- changed line color in Line Graph
- go to Bar Graph
- change the same line color to another

**Comment by baozi90** [comment]
Actually, it does that when I just stay on the Bar Graph and change the color, without changing from Line or Scatter either.

**Comment by Rek3650** [comment]
This is probably my fault. changed these to canvases instead of spans with a background. I'll look into it.
