### ISSUE TITLE
NaN values break chart

### ISSUE THREAD

**Issue by melissay94** [RITAccess/data-analyzer#117]
If you load a CSV that has NaN values in the parts of the table that only accept number values, then the whole chart ends up breaking. Possible solution to this problem is to simply have not accepted values exchanged with zeros instead.

**Comment by melissay94** [comment]
Added check for when the file is first read in that looks to see if there is a non numerical value or a blank space where a numerical value should be. If this is true, then a zero is placed in as a place holder

**Comment by smcintosh881** [comment]
If the zero is added to the table, then the lowest value in the table will be a zero. Would this be an issue if the user left the empty space in the CSV on purpose, so its not technically the lowest value?

**Comment by melissay94** [comment]
If a user adds an empty space to the table, it breaks the graph when its loaded. So the zero acts as a place holder since blank spaces are not good.
