### ISSUE TITLE
Stop Feature

### ISSUE THREAD

**Issue by baozi90** [RITAccess/data-analyzer#118]
Does the pause/play button stop or just pause the audio? If it doesn't stop, is it possible to add the stop feature?

The stop feature ends the current audio completely, and when switched to another row it starts playing the new row instead of continuing from the last row that was playing. The stop feature may be in the form of another button next to the play/pause button.

On the other hand, that feature could be implemented right when the user switched to another row. (For some reason, I think this might cause some sort of problem/trouble, somehow.)

**Comment by jmiller656** [comment]
As of now, when the row is switched, the player should start from the beginning on that new row. I haven't been able to test it for safari, but it should behave that way everywhere else.

**Comment by baozi90** [comment]
Okay, I think it does work on Safari too. 

Another thing I've noticed: in Firefox and Chrome:
- when I play row 1, for example
- and go to row 2 while row 1 is playing
- then click on pause/play button, in this case it pause row 1 audio
- then click on pause/play button again, row 1 continues to play
- after row 1 finished, click on the pause/play button again
- row 2 now continues

Since the audio last shorter on Safari, that might be why this doesn't happen on Safari. 

(test3.csv was used)

**Comment by baozi90** [comment]
Regarding the last comment, both Firefox and Chrome still seems to be doing the same thing I've described earlier, the continuing last row after switching to another row thing.

**Comment by jmiller656** [comment]
Looks like my fix to #129 broke my previous fix for this issue. It should be working now.

**Comment by baozi90** [comment]
Yup, it's working again.
