### ISSUE TITLE
Reset Site Background/Text Color; Blank Text Input Field

### ISSUE THREAD

**Issue by baozi90** [RITAccess/data-analyzer#122]
When reset the site background color, it sets both the site background and text color change text input field to blank. On the other hand, when reset text color, only the text color input field is set to blank.

In this case, only the corresponding color change input field should be set to blank. In other words, site background reset should not set text color change input field to blank, and only set it's own input field to blank, as the text color change reset did.

**Comment by Rek3650** [comment]
It should be noted this only happens when high contrast is turned on.

**Comment by Rek3650** [comment]
We are going to remove the high contrast option for the text. When a user has both text and site high contrast on changing one overrides the other. This way, when a user changes the background then the text color it does not undo the change to the background color.

**Comment by baozi90** [comment]
Personally, I like that contrast feature for text color because I only need to make the change for the text color and the background changes automatically. 

In this case, if the contrast feature were to be taken away, I'd have to go and change the background color after changing the text color.

**Comment by melissay94** [comment]
I vote that we keep the high contrast button for both background and text as now if you forget to turn off high contrast before changing text color, you can just switch it off and it'll go back to the previous background color you had.

**Comment by melissay94** [comment]
Compromised on the high contrast buttons, their default state is going to be off instead of on.

**Comment by baozi90** [comment]
The original issue still isn't solved though.

**Comment by jmiller656** [comment]
This only happens with high contrast. That is how it should work since it is resetting the text as well when high contrast is on.
