### ISSUE TITLE
Validate Codes

### ISSUE THREAD

**Issue by baozi90** [RITAccess/data-analyzer#124]
Are we going to validate the codes such as HTML and CSS, and maybe JS too, using sites like this below?

HTML: https://validator.w3.org
CSS: https://jigsaw.w3.org/css-validator/

Related to issue #60

**Comment by melissay94** [comment]
I would only worry about validating it if everything wasn't working together. Also JS validates in the console by erroring out, that is what the "use strict" at the top of each page does, makes sure we only use proper syntax in our JavaScript.
