### ISSUE TITLE
Print Page Color Matching Original Site Page

### ISSUE THREAD

**Issue by baozi90** [RITAccess/data-analyzer#125]
As of now, the print page color is set to be the original color theme. Should the print page inherit the color changes in the original site?

**Comment by jmiller656** [comment]
No, because if the background is black or any other dark color, it will basically be wasting ink. The original theme is fine.

**Comment by baozi90** [comment]
Actually, what if the user don't actually print it but save as PDF? #126

**Comment by jmiller656** [comment]
That's a good point. Should have this working soon
