### ISSUE TITLE
Change Header Title Color When Printing 

### ISSUE THREAD

**Issue by baozi90** [RITAccess/data-analyzer#126]
Similar to issue #125:

If the user wants to print out the background, is it worth the effort to figure out a way to change the site title to a contrast color (white) if the background is dark (black)? So far, I made a white font border over the title:

<img width="477" alt="screen shot 2015-07-15 at 14 39 22" src="https://cloud.githubusercontent.com/assets/11864006/8706711/47b435fe-2aff-11e5-916d-f7787ec07557.png">

The user might "print"/save it as PDF.

**Comment by jmiller656** [comment]
This won't be necessary, since we'll just have the page inherit the background color for the background and not the header.

**Comment by baozi90** [comment]
The header is taken out and leaving only the site title, which is in black when printing.

**Comment by jmiller656** [comment]
Ok. I just pushed something that should fix this. Do you want to try it out and tell me if you still have the problem?

**Comment by baozi90** [comment]
What does it do?

**Comment by jmiller656** [comment]
It formats the print page to use the correct colors for the background, graph background, all text, and table borders.

**Comment by baozi90** [comment]
Oh okay, I see the change now. Was testing in the main site...

For Chrome, I noticed the font border doesn't show up when printing.

**Comment by baozi90** [comment]
Also, the print page is missing the borders when background and text changed (border color didn't change):

[borders]

<img width="880" alt="qq20150715-1 2x" src="https://cloud.githubusercontent.com/assets/11864006/8708622/25048af2-2b0b-11e5-816f-225f368ef9cf.png">


[no borders]

<img width="841" alt="qq20150715-2 2x" src="https://cloud.githubusercontent.com/assets/11864006/8708628/2cb2a130-2b0b-11e5-888a-d316fa0381f2.png">
