### ISSUE TITLE
Graph Text Color

### ISSUE THREAD

**Issue by baozi90** [RITAccess/data-analyzer#127]
When changing the text color, with and without contrast for text color, the graph text color do not change along with other texts of the site. 

Without contrast for graph color, graph text color changes to the user input color when changing the graph background color. 

Is this supposed to happen?

**Comment by jmiller656** [comment]
I think that was added recently. It shouldn't happen, because we want to always guarantee that the labels are visible, otherwise the graph would be somewhat pointless. The text color for the graph shouldn't be changing with the text color for the rest of the page. I'll fix this.
