### ISSUE TITLE
Wiki Page

### ISSUE THREAD

**Issue by baozi90** [RITAccess/data-analyzer#130]
So far, I've basically copy and paste the information we have on the home page. Are we going to add any thing else to the wiki page?

**Comment by melissay94** [comment]
We are currently writing a tutorial on how to each aspect of the site in detail, so once that is done, we can add that to the wiki page as well.

**Comment by baozi90** [comment]
Okay.

**Comment by jmiller656** [comment]
Here's a link to a google doc of the tutorial:
https://docs.google.com/document/d/1lVfjMHA6KmR_IKlUpfKJxVybzjYmcyZV4xv8R3x2rD0/edit?usp=sharing

**Comment by baozi90** [comment]
I've added the subtitle/subsections links of the tutorial to the wiki sidebar, so we can just put the entire tutorial in one page even though it's really long. 

Will wait for the tutorial page to get longer to test if the sidebar links are working.

**Comment by smcintosh881** [comment]
Just uploaded the tutorial into the wiki page. Each sidebar option has the appropriate text.
