### ISSUE TITLE
Pause/Play Button

### ISSUE THREAD

**Issue by baozi90** [RITAccess/data-analyzer#131]
Does the pause/play button pause or stops and restart audio from beginning? It seems to stop and restart. (Tested in Chrome so far.)

(I might've asked a similar if not a same question.)

**Comment by jmiller656** [comment]
It should resume if you stop part of the way through. This was an earlier issue at one point.

**Comment by jmiller656** [comment]
It looks like it broke somewhere for firefox and chrome, but not safari. I'll fix it.
