### ISSUE TITLE
Need a Way to Stop, Not Just Pause, Currently Playing Audio

### ISSUE THREAD

**Issue by baozi90** [RITAccess/data-analyzer#132]
Similar/almost exactly the same to issue #118 with the stop feature: 

While testing out the audios, I listened half way through and wanted to restart/stop, but I couldn't find a way to. I would just wait for the current audio to finish playing. An additional of a stop feature for this case would be really helpful for me to restart playing the current row audio.

This would probably be another button.

**Comment by jmiller656** [comment]
![stopbutton](https://cloud.githubusercontent.com/assets/8846806/8747971/4aa04494-2c65-11e5-8db7-39a1f3000d4a.png)

Something like this (minus the wrapping somehow)?

**Comment by baozi90** [comment]
Yeah, something like that.

**Comment by Rek3650** [comment]
:-1: Buttons

**Comment by baozi90** [comment]
How about a drop down with options: (1) Play, (2) Pause, (3) Stop, and one button for it to work.

**Comment by baozi90** [comment]
I will just add the visual of the three buttons.

**Comment by jmiller656** [comment]
When you make them, set the onclick to player.play() player.stop() and player.pause() for the corresponding buttons. I will work on modifying the audio functions to handle this.

**Comment by baozi90** [comment]
Okay.

**Comment by baozi90** [comment]
Original code for play/pause button:

            <button id="playButton" onclick="playStopAudioButton()" aria-label="Play Pause Toggle">
              <i id="icon" class="fa fa-eject fa-2x fa-rotate-90" ></i></button>

**Comment by baozi90** [comment]
I'm not sure if the id="icon" is used for anything, but I've changed it to id="playToggle" for the play button.

**Comment by baozi90** [comment]
How does the buttons on the right versus on the left look?

[Left]
(1)
<img width="815" alt="screen shot 2015-07-17 at 10 33 50" src="https://cloud.githubusercontent.com/assets/11864006/8749413/5c0479b2-2c6f-11e5-94b2-0c187816942e.png">

(2)
<img width="818" alt="screen shot 2015-07-17 at 10 33 40" src="https://cloud.githubusercontent.com/assets/11864006/8749414/5fb9a9c4-2c6f-11e5-9ac3-5a920aae1dce.png">


[Right]
(1)
<img width="820" alt="screen shot 2015-07-17 at 10 32 00" src="https://cloud.githubusercontent.com/assets/11864006/8749376/2fb2b18a-2c6f-11e5-8eb6-f63887657140.png">

(2)
<img width="812" alt="screen shot 2015-07-17 at 10 32 10" src="https://cloud.githubusercontent.com/assets/11864006/8749381/3a4fcda8-2c6f-11e5-824b-0d5f723e9971.png">

**Comment by jmiller656** [comment]
I'd probably say left because everything else is aligned to the left

**Comment by baozi90** [comment]
Okay.
