### ISSUE TITLE
More Instruments for Safari

### ISSUE THREAD

**Issue by baozi90** [RITAccess/data-analyzer#133]
One of the things to consider, if possible: find more instruments for Safari. (Current ones are also really annoying to listen to and seems to cause/bring buzzing noises.)

**Comment by jmiller656** [comment]
These are the only sounds that will work for safari. Safari does not support soundfonts like all of the other browsers, so the graph has to be sonified using raw sound data. This is most simply generated using a sine wave. I have also included more advanced waves (square, sawtooth, and triangle), and these are really the best that we can do as of now. If safari ever becomes compatible with midi instruments, then we can add those into safari.

**Comment by baozi90** [comment]
Should we close this or put on hold for now?

**Comment by jmiller656** [comment]
We should close it. The ball is in apple's court.
