### ISSUE TITLE
Hover Color On When Audio Buttons Are Clicked

### ISSUE THREAD

**Issue by baozi90** [RITAccess/data-analyzer#134]
While the audio is playing, the play button will appear as it is when hovered over. Same goes to the pause button when the audio is paused. Not sure if the same applies to the stop button and how.

It will be something like this (as the audio is playing): 
<img width="453" alt="screen shot 2015-07-17 at 14 07 02" src="https://cloud.githubusercontent.com/assets/11864006/8753899/54819846-2c8d-11e5-82c0-7e1811659c93.png">

(I hovered over the button before taking the screenshot.)

**Comment by jmiller656** [comment]
I think the onFocus is doing that. Since it is selected when it is clicked, the button is focused, so it stays black.

**Comment by Rek3650** [comment]
they are currently being focused. If a user presses space o enter they will click the button.

**Comment by baozi90** [comment]
Okay, I see it now, but only on Chrome and not Firefox or Safari though.

**Comment by Rek3650** [comment]
Really? I just tried it in Safari and Firefox and it worked in both.

**Comment by baozi90** [comment]
Yup, still doesn't work on Safari and Firefox for me. 

Not sure if it make a difference: I'm clicking on it without VoiceOver or anything, just normal way like I did in Chrome.

**Comment by baozi90** [comment]
For Chrome, let's say I'm playing the audio and the play button is "on"/turns color, and I clicked on somewhere else other than the play button itself, it'd go back to the white button/back to normal while the audio is still playing.

**Comment by Rek3650** [comment]
Thats because it isn't related to the audio playing. Its related to what the browser is currently focusing.

**Comment by smcintosh881** [comment]
It works for me on all 3 browsers. The button only changes color when you are currently on it, either with tab or click. I don't think this is an issue with the current version of the application but possibly a cache issue with your browsers.

**Comment by baozi90** [comment]
Deleted all browser history and everything else including caches: 

Safari works with VoiceOver open when tab over. When without VoiceOver, tab doesn't work, just skips over it. When clicking on the buttons, also without VoiceOver on, no hover looking thing/feature (hover focus) appear. 

Firefox: With VoiceOver hover focus works. Without VoiceOver, tab works, click does not.

Chrome: With VoiceOver hover also works like the other two browsers. Without VoiceOver, tab also works. Click does work, but when clicked somewhere else it disappears >> this would be how it'd be with the stop button since it only stops the audio but the play and pause is still functioning so it doesn't make since in these cases. 

Above are the situations I'm seeing in my browsers.

**Comment by baozi90** [comment]
Additionally:
For all browsers when VoiceOver is on and the buttons like the play buttons is clicked one/pressed enter for and the audio is playing, if you clicked or tab on something else the hover focus disappears as well. This makes it looks like the audio isn't playing anymore like it did in Chrome without VoiceOver.
