### ISSUE TITLE
Scatterplot disappears when hidden and brought back

### ISSUE THREAD

**Issue by jmiller656** [RITAccess/data-analyzer#139]
If you load test1.csv as a scatter plot, hide the line, and bring it back, only the regression line appears. I believe this has to do with whatever is measuring the y values of scatter plot points because each of the points has NaN for a y value when it is brought back from being hidden.

**Comment by smcintosh881** [comment]
The issue only occurs when there is only one line. If you do test4.csv the first line you bring back will just bring back the regression. The second line brought back will show two lines.
