### ISSUE TITLE
Move Data Table

### ISSUE THREAD

**Issue by melissay94** [RITAccess/data-analyzer#146]
A lot of kids would have preferred that the data table be placed up higher on the web app instead of being below other parts.

**Comment by smcintosh881** [comment]
Where would be better?

**Comment by baozi90** [comment]
Maybe move the audio controls above the graph and the data table would be right under the graph?

**Comment by smcintosh881** [comment]
I think that would be good

**Comment by baozi90** [comment]
I've moved it above the graph. Also, should we add a header like below?

<img width="862" alt="qq20150729-6 2x" src="https://cloud.githubusercontent.com/assets/11864006/8962599/794ca0ca-35e9-11e5-8827-c98d4789728b.png">

**Comment by smcintosh881** [comment]
I think a header would be good

**Comment by melissay94** [comment]
Hey guys I should have been more clear, they want it to be the first thing they access when going through the page. So maybe place the audio controls under the table. That's what I meant for higher on the page, higher accessibility wise.

**Comment by baozi90** [comment]
How's this:

<img width="1280" alt="qq20150730-1 2x" src="https://cloud.githubusercontent.com/assets/11864006/8989117/16bc5b88-36b8-11e5-9b97-ef4b971e4b87.png">

**Comment by smcintosh881** [comment]
I think that looks good

**Comment by baozi90** [comment]
Alright, I'll push it.
