### ISSUE TITLE
Letter still accepted as input in main table area

### ISSUE THREAD

**Issue by melissay94** [RITAccess/data-analyzer#147]
The data table has reverted to allowing letters as valid input into the data area. This should no longer be the case, as a check for that was implemented if someone can just check on that.

**Comment by smcintosh881** [comment]
Do you know what the file name is?

**Comment by Rek3650** [comment]
The data table? I tried putting letters in anywhere other than the labels and they always reverted back. Is this issue specific to a graph type?

**Comment by smcintosh881** [comment]
You can do it in Bar Graph only
Line and scatter work normally

**Comment by baozi90** [comment]
Additionally, in Safari and Chrome, Bar Graph accepts letter input (as mentioned above): 

If changed to Scatter or Line, both will show the inputs as "NaN". When any letter is entered, the "NaN" will show as the preciously entered letter back in the Bar Graph table, unless a number is entered.

Firefox just stays as "NaN" unless a number is entered.
