### ISSUE TITLE
Pop-up Windows Don't Respond With Browser Size Change

### ISSUE THREAD

**Issue by baozi90** [RITAccess/data-analyzer#150]
When any of the Load CSV, Create New Table, and Help pop ups is open and try to resize the browser, the pop up window do not "center" itself accordingly.

A better style instead of 

dialogbox.style.left = (winW / 2) - (550 * .5) + "px";

might be needed.

**Comment by smcintosh881** [comment]
I agree. Any thought on what to use instead? Is there an auto align center or something?

**Comment by baozi90** [comment]
There is, but it doesn't seem to be working.

**Comment by smcintosh881** [comment]
ok. It might have something to do with the white fade screen that covers the background?

**Comment by baozi90** [comment]
Could also be either something to do with being in JS or that it's a "pop up".
