### ISSUE TITLE
Pop Up Size is Now Responsive Instead of the 550px Width

### ISSUE THREAD

**Issue by baozi90** [RITAccess/data-analyzer#154]
Not sure if it's related to the changes made to fix either issue #150 or #151, but is it okay that the size of the the pop ups, mainly Load CSV and Create New Table, now changes according to the browser size change?

Might need to modify this to do so:
<img width="721" alt="qq20150730-3 2x" src="https://cloud.githubusercontent.com/assets/11864006/8989799/62919da8-36bc-11e5-86ab-d93e1794209b.png">

**Comment by smcintosh881** [comment]
do you want it to be the fixed 550px?

**Comment by baozi90** [comment]
It was like that before. As of now, the limit for the pop up to expand seems to relate to the size of the content div, which is probably 800px (fixed width). If it expands more than it already is, then it would look too good (too much spacing). That's why I'm not sure about it..

**Comment by baozi90** [comment]
Actually, the size is percentage, I think, a fixed size would be better.

**Comment by smcintosh881** [comment]
Ok . I made it percent because fixed width gets a little wonky with the resizing of the whole page

**Comment by baozi90** [comment]
Yeah, doesn't look too good with px. I'll modify it a little and use percentage instead.

**Comment by smcintosh881** [comment]
I think the latest push looks good

**Comment by baozi90** [comment]
I think that one still extents with large width though.

**Comment by smcintosh881** [comment]
yea it can get as big as the page goes. There is no set max width

**Comment by smcintosh881** [comment]
Is this still an issue?

**Comment by smcintosh881** [comment]
Can this be closed?

**Comment by baozi90** [comment]
When the browser gets small, it still squeeze everything inward.

**Comment by smcintosh881** [comment]
I think it works better to resize with the page because thats how other elements on the page are

**Comment by baozi90** [comment]
<img width="605" alt="qq20150731-1 2x" src="https://cloud.githubusercontent.com/assets/11864006/9010209/9a45bc0e-3773-11e5-8d2c-fb4f8e007ffd.png">



Like this?

**Comment by smcintosh881** [comment]
Yea

**Comment by baozi90** [comment]
Wait, for other elements, the contents doesn't resize though. Only the start with instructions does because it only has text or something.

**Comment by smcintosh881** [comment]
Yea on the front page. I think thats to one it should match because it most likely will be a popup on that page. We could do a min width that way it doesnt get too small

**Comment by baozi90** [comment]
So far, it only gets as small as the screenshot above, if that looks good then don't think a min width is needed.

**Comment by baozi90** [comment]
Oh, never mind, I think I get what you mean by the min width now.

**Comment by baozi90** [comment]
I've added some media screen properties for Load CSV and Create New Table pop-ups. Now should response better when browser size is smaller and would not wrap the text, select/input fields, and buttons anymore.

**Comment by baozi90** [comment]
This is what I have right now:

About the wrapping for the Load CSV, it doesn't wrap on Chrome. Wraps on Safari. Do not wrap on Firefox, but doesn't change the left margin to 5%. 

Will continue looking into it.

**Comment by baozi90** [comment]
Safari wrap and margin looks good now.

The margin left 5% on Firefox still doesn't seem to work. Can't find any thing wrong with the research I've done just yet.

**Comment by baozi90** [comment]
Seems to be working with all browser (Firefox, Safari, and Chrome) now.
