### ISSUE TITLE
Create New Table Pop Up Border

### ISSUE THREAD

**Issue by baozi90** [RITAccess/data-analyzer#156]
Create Table pop up still seems to inherit some styles of Load CSV pop up after changing the names of the corresponding id's.

Changed the id names so they make more sense, unique for each pop up, and can be easier to edit css property.

**Comment by smcintosh881** [comment]
![screen shot 2015-07-30 at 4 13 34 pm](https://cloud.githubusercontent.com/assets/9065471/8993903/fa2c37c2-36d5-11e5-9456-22ae082a3fc4.png)

Is this what you're talking about?

**Comment by baozi90** [comment]
Yeah.. that's the one :P

**Comment by smcintosh881** [comment]
Some element probably didn't get renamed correctly or soenthing. Ill go through your last two commits to see what happened

**Comment by smcintosh881** [comment]
There was a missing div section for the create new table pop up. The upload one had it.
