### ISSUE TITLE
Accessibility of html elements labeled Group

### ISSUE THREAD

**Issue by melissay94** [RITAccess/data-analyzer#16]
There are certain elements on the page that when tabbed over simply say group as their name, ex the ends of the sliders and the table. Names for these objects will have to be assigned in order to make it more accessible. 

WAI-ARIA documentation for using web accessibility: http://www.w3.org/WAI/intro/aria.php

**Comment by melissay94** [comment]
ALL DONE (not really this is a test/learning exercise)

**Comment by melissay94** [comment]
Not actually fixed

**Comment by smcintosh881** [comment]
I'm going through the page using VoiceOver and in the Line Data area, each line's information is read, but it doesn't pick up the last line of text which is the "Total Data Summary". Not sure if this is just my computer or if it is happening to on others.

**Comment by baozi90** [comment]
There wasn't anything read out other than the shape line on firefox, and "Enter new line 1 color, edit text" was read for Safari and Chrome. -- does not read the "Total Data Summary" for me either

For the play button, only Firefox reads out "Play Toggle" and both Chrome and Safari reads "button" and shows "image, button".

For the Load CSV button, Chrome sometimes skips over it and goes to the play button, but both Safari and Firefox goes to it before the play button. -- agreed with the tab index thing

**Comment by smcintosh881** [comment]
Just ran the VoiceOver auto-read where it reads everything on the page and it read all the information in the summary box, but it was very inefficient try running the command: control + option + A 
There is a lot of duplicated information.

**Comment by baozi90** [comment]
Just added some tab index, now should read the title "Line Data" when tab to the box.

**Comment by smcintosh881** [comment]
All the tabbing seems to be working except Total Data Summary at the bottom of Line Data is not readable yet.

**Comment by smcintosh881** [comment]
There is a bit of an issue when you open the graph and the black pop up asks what type of graph. The reader does not pick up "Choose a type of graph:" as readable. I'm trying to find a way to have the screen reader read this so that people know the point of the pop up

**Comment by smcintosh881** [comment]
The current way the tabbing is set up when the pop-up shows up you have to tab over "Load CSV" and "Create New Table" I think this might be a problem because they might not know that there is a pop up so they might click "Create New Table" thinking that it will create the table for their CSV. I'm not sure if people would actually be confused by this, but I think there is a possibility. I think the tab order could be changed or have a sound play when the pop up shows up

**Comment by smcintosh881** [comment]
VoiceOver works for Chrome. I am testing FireFox and Safari, but I think accessibility is almost accomplished. It passes the accessibility tests with only a few warnings for things like contrast ratio

**Comment by smcintosh881** [comment]
All three browsers are fully functional with VoiceOver. Should we test it with other screen readers or does just VoiceOver need to work?
