### ISSUE TITLE
Browse/ Load CSV button says multiple files have been loaded

### ISSUE THREAD

**Issue by melissay94** [RITAccess/data-analyzer#18]
When you are selecting files, you can select multiple. While it only displays one file in the browser, the label next to the button says how many files were initially selected. We may want to look into a way of having the native file chooser limit the number of files that can be chosen if possible.

**Comment by erl7902** [comment]
changed     <input type="file" id="files" name="files[]" multiple /> to     <input type="file" id="files" name="files[]" />, no longer allows for multiple files to be uploaded at once
