### ISSUE TITLE
Button for loading the CSV looks different in Firefox 

### ISSUE THREAD

**Issue by baozi90** [RITAccess/data-analyzer#22]
Button for loading the CSV looks different in Firefox compared to Chrome and Safari. It could have something to do with the webkit and moz properties in the group css for input[type=file]. 

https://developer.mozilla.org/en-US/docs/Web/CSS/Reference/Mozilla_Extensions
http://css-infos.net/properties/webkit
http://geniuscarrier.com/how-to-style-a-html-file-upload-button-in-pure-css/

**Comment by jmiller656** [comment]
http://www.quirksmode.org/dom/inputfile.html
