### ISSUE TITLE
Graph dots be different shapes

### ISSUE THREAD

**Issue by smcintosh881** [RITAccess/data-analyzer#26]
Currently on the graph each data point is marked by a circle. Dr. Ludi suggested we try to make each line have different shapes, like triangle, square, circle. Right now color is the main way to tell what line is what, however, not everyone can see the colors. The main problem is to find a way to identify the lines without the colors.

**Comment by smcintosh881** [comment]
After reading the chartjs docs (http://www.chartjs.org/docs/) I don't think that changing the shape of the circle is possible However, maybe we could make each line have slightly larger dots because radius size can be changed. So Line1 would have smaller circle/dots than Line2 and so on, the last line having the largest dots.

**Comment by smcintosh881** [comment]
https://github.com/nnnick/Chart.js/pull/527

From what I've been looking at there definitely can be circle and squares (not sure how to actually set them). We could also look into using different weighted dash lines to show the difference.

Whatever we end up doing we need to display what line number goes with what shape or dashed weight. 
We could put it down in the color editor area or someplace else.

**Comment by jmiller656** [comment]
I've been experimenting with the Chart.js source and have gotten a few different unique shapes to work. Here's a screenshot (squares purposely made red in order to emphasize them, this will be reverted to the original shape color)
![screenshot from 2015-06-04 11 25 23](https://cloud.githubusercontent.com/assets/8846806/7987613/9335aec2-0aac-11e5-8f01-652643c287d8.png)

**Comment by smcintosh881** [comment]
https://developers.google.com/chart/interactive/docs/points

This is all the different shape options that Googles chart.js equivalent has.

**Comment by baozi90** [comment]
"Whatever we end up doing we need to display what line number goes with what shape or dashed weight. We could put it down in the color editor area or someplace else."

There might be too much scrolling if added to the color editor area and will be harder to compare to the chart if too far away.

**Comment by smcintosh881** [comment]
Maybe create an area for it above or below the data plot section so it is closer to the graph. 
![screen shot 2015-06-04 at 11 55 09 am](https://cloud.githubusercontent.com/assets/9065471/7988302/afbddde0-0ab0-11e5-8426-64d0416d7ab1.png)

**Comment by smcintosh881** [comment]
And decrease the spacing a little bit. Maybe bring it down from 60px to 40px?

**Comment by baozi90** [comment]
Maybe above the graph? If below, it makes the data plot seem out of place. :/ 

And I think decrease the spacing sounds good.
