### ISSUE TITLE
Addition of Other Chart Types

### ISSUE THREAD

**Issue by melissay94** [RITAccess/data-analyzer#29]
Add the possibility for other chart types such as a bar graph and scatter plot for users to choose from. Each chart would also have different audio representations as well. 

Bar graphs would play either by a section of bars or play a row of data from the chart

Scatter plots would play a "note" as it reached it on the plot moving from left to right. You could select different layers of the scatter plot to play. It could also have the option of playing the regression line. 

Also, chart.js has the option of a bar graph, but not one for a scatter plot so that would need to be created from scratch in the chart.js code as an option.

**Comment by smcintosh881** [comment]
Using the line graph with an "invisible" line connecting the dots works for the scatter plot visual.

**Comment by smcintosh881** [comment]
One of the main uses for the scatter plot is to see how closely associated the points are, thats what the regression shows. It might not sound good with the current library, but as the line was played, play all the dots of data around it. If the point was above the regression higher, if it is below the line play lower. That way people can visualize the clusters of data in relation to the line.

**Comment by erl7902** [comment]
It might be hard to see the overarching trends in the data though if the line of regression sounds like a flatline, though. 

I'd like to try my hand at creating the scatterplot from scratch; sounds like an interesting project

**Comment by smcintosh881** [comment]
The regression line could be played as one continuously increasing/decreasing note (like a slide whistle) and while that is playing play the data points around.

**Comment by jmiller656** [comment]
Making a dropdown menu for chart types while files are loaded. Here's some code that describes how it will happen https://jsfiddle.net/AwFE3/8/

**Comment by erl7902** [comment]
Scatterplot added - working on putting in a line of regression for the data

**Comment by erl7902** [comment]
Scatterplot working except for the dynamic steps on x axis - no additional chart types to be added
