### ISSUE TITLE
Have a Print Friendly Style Option

### ISSUE THREAD

**Issue by melissay94** [RITAccess/data-analyzer#31]
If users wish to print out their work, such as if they are turning it in with homework. The changes for this would be done in the style.css and would simply involve hiding elements such as the load button, the play audio options, the slider over the chart, and the changing of the color text fields and check boxes.

So what should be left is the chart, the table, and the summary information.

**Comment by baozi90** [comment]
Load button, play audio options, related texts and the slider (plus overlay) are taken out. Color text fields and check boxes are left as it is as discussed.
