### ISSUE TITLE
Save/ Download Table Changes

### ISSUE THREAD

**Issue by melissay94** [RITAccess/data-analyzer#32]
Since users are able to edit the data in the table while using the app, we want to give them the option of saving/ downloading the new version of their data to their computer. It would simply download the new file as a CSV which they could then also use in other places if they needed to.

**Comment by baozi90** [comment]
Download button added and the onclick function is working as it should.

**Comment by baozi90** [comment]
Except Safari??

**Comment by jmiller656** [comment]
Could somebody try this on safari and tell me if it works?
http://jsfiddle.net/nkm2b/2/

**Comment by jmiller656** [comment]
Used php and file now downloads in safari, chrome, and firefox
