### ISSUE TITLE
Font size and green arrows

### ISSUE THREAD

**Issue by smcintosh881** [RITAccess/data-analyzer#33]
The font size is smaller and there are little green arrows located in libs/SlickGrid/examples/examples.css 

Do we need these different styles? Maybe do some merging so that we only have one style sheet.
Font size is around line 5: font-size: 8pt 
and the green arrows are around line 26: "  background: url("../images/arrow_right_spearmint.png") no-repeat center left;"

Removing both of those will restore the original look.

**Comment by erl7902** [comment]
This is a problem with slickGrid - they had a lot of other stuff in their source code that I just grabbed. I'll sort it out once we get the merge problems fixed

**Comment by smcintosh881** [comment]
We've already located where the problems are but we are waiting for the new version to be pushed
