### ISSUE TITLE
Find and implement a new (better) audio library

### ISSUE THREAD

**Issue by Rek3650** [RITAccess/data-analyzer#34]
[Jsfx](https://github.com/loov/jsfx) is passable as an audio library but there are probably better ones available. After some research I found two that might meet our needs. 
1. [Tone.js](https://github.com/TONEnoTONE/Tone.js)
2. [timbre.js](http://mohayonao.github.io/timbre.js/).

Already supported with Jsfx:
* Play a large range of sounds
* Allow for audio playback to be stopped
* Adjustable speed

Additional goals for a new library:
* Better sound quality
* Support multiple sounds at once
* More types of sound (instruments, wave shapes)

**Comment by jmiller656** [comment]
Timbre.js has now been fully implemented and is currently replacing jsfx. We now support waveforms on all browsers and midi instruments on all browsers except safari.
