### ISSUE TITLE
Put data plot and line data in scrolling fields

### ISSUE THREAD

**Issue by jmiller656** [RITAccess/data-analyzer#39]
For larger data sets, the page becomes very long and tedious to scroll through. It would be more convenient to have the data plot and line data fields be scrollable.

**Comment by baozi90** [comment]
Both the data plot and line data in the same scroll?

**Comment by jmiller656** [comment]
I think different scrolling fields for both would be better

**Comment by baozi90** [comment]
I've added the scrolls but since it needs to have a fixed height to work, I'm not sure if have the add row, column, and download buttons are okay to be far from the table like in test1.csv.

**Comment by jmiller656** [comment]
I think it will be ok since they will most likely be accessed by tabs anyways

**Comment by baozi90** [comment]
Okay.
