### ISSUE TITLE
Line Data - N/A for different graphs

### ISSUE THREAD

**Issue by baozi90** [RITAccess/data-analyzer#40]
The name "Line Data" doesn't seem applicable when different type of graph is being selected. Same goes with the "Line 2, Line 3, ..."

**Comment by smcintosh881** [comment]
We could change "Line Data" to "Graph Data" 
We could do Set 1
Each line is a set of data.  
Another question would be does Scatter Plot need Average? Maybe we could replace Average on the Scatter Plot with the correlation?

**Comment by smcintosh881** [comment]
I also think that Data Plot could be called Data Points

**Comment by smcintosh881** [comment]
Data Plot now is Data Table
Line Data is now Graph Data
and each Line # is now Set #
