### ISSUE TITLE
Not All Columns Print

### ISSUE THREAD

**Issue by baozi90** [RITAccess/data-analyzer#41]
When printing, the columns that can be access by horizontal scrolls needs to be able to be printed, somehow.

**Comment by baozi90** [comment]
http://stackoverflow.com/questions/2747045/print-table-with-horizontal-scroll

**Comment by jmiller656** [comment]
Table prints separately now, just need to cut it so it fits on the paper

**Comment by jmiller656** [comment]
Prints graph, summary data, and entire table now.
