### ISSUE TITLE
Re-adjust window when line is no longer visible

### ISSUE THREAD

**Issue by smcintosh881** [RITAccess/data-analyzer#42]
When you uncheck a line that was very big, and the ones left are much smaller the window stays at the size to include the largest. Would it be possible to have the graph window re-adjust to the changes to better view the smaller line.

**Comment by jmiller656** [comment]
Just changed the way the checkboxes work. Graph resizes now. Lines are removed from the dataset and replaced when the checkbox is rechecked.
