### ISSUE TITLE
Adjust size of text box of the table as the inputed number increases

### ISSUE THREAD

**Issue by baozi90** [RITAccess/data-analyzer#44]
Adjust size of text box of the table as the inputed number increases. For example, "1000" and larger will show up like "1...".

**Comment by smcintosh881** [comment]
Its mostly a problem when printing. I also noticed that if you have a cell in the table highlighted and then go to print it the cell is still highlighted (Its fine for the VoiceOver navigation. It will still read it as 1000 ).

**Comment by jmiller656** [comment]
The printed table can support large numbers now without needing a horizontal scroll. If the number becomes too large, it is either text-wrapped or put into exponential notation.
