### ISSUE TITLE
Take Out Extra Space When First Visit the Site

### ISSUE THREAD

**Issue by baozi90** [RITAccess/data-analyzer#50]
When the index loads, there is a lot of empty/extra spacing below the "About" section.

**Comment by smcintosh881** [comment]
I got rid of some of it. It looks fine on the larger screen now. How does it look on the smaller?

**Comment by baozi90** [comment]
Looks a lot better now, but maybe more if possible. 
![screen shot 2015-06-15 at 11 46 00](https://cloud.githubusercontent.com/assets/11864006/8163968/33e9af94-1354-11e5-8522-71d518fef235.png)

**Comment by smcintosh881** [comment]
Ok, Ill keep messing with it

**Comment by smcintosh881** [comment]
So the reason for the space is the graph canvas and the data plot div. The div cannot be hidden because it does that weird disappear thing. The canvas also must be displayed in order for the graph to work.

**Comment by baozi90** [comment]
Yeah, I noticed that; (was thinking maybe there's a way to set the content height when first load -- not sure how or even possible).

**Comment by smcintosh881** [comment]
I didn't find anything but maybe there is something.

**Comment by baozi90** [comment]
I moved the about start tag out of the content tag so it's a separate one from the graph and everything. Then I set the content display to none and tried the display block in main.js after taking out all of the other display none, other than for the content, in the index. 

In this case, some such as the graph and the overlay doesn't show up.

**Comment by baozi90** [comment]
Used 

position: absolute; top: -9999px; left: -9999px;

to hide the content tag.

**Comment by baozi90** [comment]
Used 

position: absolute; top: -9999px; left: -9999px;

to hide the content tag, and override those codes in the main.js file so content would appear when load CSV and create new table.
