### ISSUE TITLE
Save Table Data When...

### ISSUE THREAD

**Issue by baozi90** [RITAccess/data-analyzer#52]
Removing and adding same row and/or column back: When a row and/or column is removed and added back, the row and/or column data removed will be replaced will all zeros when the same row and/or column is added right after removing it. 

In this case, maybe add an "Undo" button?

**Comment by smcintosh881** [comment]
Could we make the remove like the visibility button. So when you check another checkbox it removes it from the graph, but if you re-check it, it adds it back. Possibly separate checkboxes, possibly joined into one.

**Comment by jmiller656** [comment]
The regular checkbox already does exactly that. I changed it from making the line transparent to making the line nonexistent in the data set in order to make the graph resize correctly.

**Comment by smcintosh881** [comment]
Is there a way to have it update the table when the line is removed that way we don't need the remove button next to the check box?

**Comment by baozi90** [comment]
I think we still need the remove button since it's mainly for the table, but maybe rename it to "Remove Row" or something instead.

**Comment by smcintosh881** [comment]
SlickGrid does work with an undo option
https://github.com/mleibman/SlickGrid/wiki/Examples

**Comment by erl7902** [comment]
A different approach to this would be to keep the original set of data, and have a cloned set that the user can modify. That way the integrity of the original data can be maintained for undo functions, and maybe even a reset function. 

That would also eliminate the need to set entire rows of data to undefined in the graph which is currently causing problems in my scatterplot code; instead, we simply pass the new dataset with the consolidated data.

**Comment by smcintosh881** [comment]
I think that would be good. We can just add a reminder on the initial page to download any changes

**Comment by smcintosh881** [comment]
I think this could be closed, we now have undo and redo buttons
