### ISSUE TITLE
Remove Specific Row/Col

### ISSUE THREAD

**Issue by smcintosh881** [RITAccess/data-analyzer#53]
When you remove the last column from the table the values change to NaN and breaks the graph.
If you remove the first row it takes the headers with it. The remove specific column is not accessible. If you remove some lines from view, then delete a line, the previously invisible lines are restored.

**Comment by jmiller656** [comment]
Fixed NaN and header problems. Still not sure what to do with the column removal to make it accessible. The problem with invisibility of lines is that the graph must redraw in order for removal to work. This completely resets the contents of the graph data div.

**Comment by smcintosh881** [comment]
I've been looking into that as well. I might have found something that works, but it needs some fixing

**Comment by smcintosh881** [comment]
I think this might help
http://mleibman.github.io/SlickGrid/examples/example-plugin-headerbuttons.html

basically it turns the headers into buttons. This example uses it to organize data in alphabetical order. I'm sure we can change it to remove a column on click. 

Maybe we could try making the remove row go up in the table too. Maybe add a button on the row label (the first column). I'm not sure if that can be done but I'll look into as an option.
