### ISSUE TITLE
Extra Button Spacing

### ISSUE THREAD

**Issue by baozi90** [RITAccess/data-analyzer#57]
On my screen so far:
There is a tiny extra spacing inside the Load CSV and Create New Table buttons for Safari, and only on Load CSV for Chrome. The ones on Firefox seems normal/just right. 

If zoom in enough, the spacing shows on the Create New Table for Chrome as well as on both Load CSV and Create New Table for Firefox. Very tiny for Firefox.

Chrome:
![screen shot 2015-06-18 at 08 35 16](https://cloud.githubusercontent.com/assets/11864006/8231210/f58351ae-1594-11e5-8680-10ae107e2bc1.png)

Safari:
![screen shot 2015-06-18 at 08 31 35](https://cloud.githubusercontent.com/assets/11864006/8231189/ceb6ce8e-1594-11e5-9f57-b6fbaba7f85c.png)

**Comment by smcintosh881** [comment]
the same occurs on mine as well

**Comment by smcintosh881** [comment]
Was this fixed? It no longer looks like that on any of my browsers?

**Comment by baozi90** [comment]
I'm not sure, but it still shows on Safari.

**Comment by smcintosh881** [comment]
Used http://geniuscarrier.com/how-to-style-a-html-file-upload-button-in-pure-css/ to fix the spacing. Probably had to do with padding.
