### ISSUE TITLE
When you Remove Row

### ISSUE THREAD

**Issue by smcintosh881** [RITAccess/data-analyzer#58]
If you try to remove one, then press cancel it will leave the cell blank, unless you click on that cell again, then it will relabel it with just the number of the row/col in relation to others in the table (the row number is the current placement in the table, not its original placement, and does not include the word Row). Essentially the table is not retaining the data that previously occupied the cell. If the cell contains a specific label (Jan, Feb, Mar) it should retain the data. If the row or column is automatically labeled (Row 1, Row 2, Row 3) then it should re-label once it is deleted. Also have the pop-up confirming cancel take the name from the row/col.

**Comment by jmiller656** [comment]
The problem with having the popup take the name from the row/col is the fact that it is triggered by the row/col changing in the table to blank, which means we'd have to get the previous value beforehand. Keeping a backup copy of the grid is a possible solution.
