### ISSUE TITLE
Add Change Background Color Option/Button

### ISSUE THREAD

**Issue by baozi90** [RITAccess/data-analyzer#63]
I'm thinking that we can add a option for changing the tan/yellow-ish background color to a preferred one. The option can be limited to around five options, or we can use the same/similar color file used for changing the graph line and point colors.

**Comment by smcintosh881** [comment]
I would ask Dr. Ludi

**Comment by baozi90** [comment]
Regarding the changing background color feature, Prof. Ludi replied:

"I think that is fine, but you will want to add in the ability to change the bg color of the graph too (it does not have to be the same as that of the text)."

So, as of now, I will try to work on making it while figuring out the right placement of the buttons and/or the option select along the way.

**Comment by smcintosh881** [comment]
I think this issue can be closed?
