### ISSUE TITLE
Clickable Header: "Graph Data"

### ISSUE THREAD

**Issue by baozi90** [RITAccess/data-analyzer#64]
When using VoiceOver on Safari, it reads that the header "Graph Data" is clickable. Also, not sure if this is related, the entire box jumps to (near) the end of the section when tabbing within the Graph Data box, while there is a scroll.

**Comment by baozi90** [comment]
Forgot to mention that about the function

onclick="openColorEditor()


Although I know it's probably why the header is clickable, I'm not sure if it's needed somewhere else or not.

**Comment by smcintosh881** [comment]
http://stackoverflow.com/questions/9707397/making-a-div-vertically-scrollable-using-css

**Comment by smcintosh881** [comment]
http://stackoverflow.com/questions/6679783/safari-scrolling-div-stuck

**Comment by baozi90** [comment]
- The header doesn't read as "clickable" anymore.
- The "jumping" is reduced by adding auto flow to the data summary section itself instead of adding to the entire Graph Data box.

**Comment by Rek3650** [comment]
Has this been fixed? I tested it in my safari and was unable to recreate the issue.

**Comment by baozi90** [comment]
Yup, still jumps in Safari when the VoiceOver is turn on. It jumps even when I click on the text input field for changing line color.

**Comment by smcintosh881** [comment]
It only does the jumping when Voiceover is on

**Comment by Rek3650** [comment]
I'm going to make another issue about this since it it technically two problems and the first one (One in the title) has been solved.
