### ISSUE TITLE
Main page resize problems

### ISSUE THREAD

**Issue by smcintosh881** [RITAccess/data-analyzer#67]
On one of the macs when you went form a small screen to a large screen the alignment of the main paragraph section was off. It doesn't do this on mine so is anyone else experiencing this issue?

**Comment by jmiller656** [comment]
Having no problems resizing in chrome or firefox on ubuntu

**Comment by baozi90** [comment]
No problems on mine either: Firefox, Chrome, and Safari.

-- Can you give a description of the problem?

**Comment by smcintosh881** [comment]
The text shifts outside of the black border box. Think it might just be Melissa's computer
