### ISSUE TITLE
Changing Graph Type 

### ISSUE THREAD

**Issue by smcintosh881** [RITAccess/data-analyzer#68]
When you change graphs types after making a certain line invisible it most likely will break completely, or show some of the bars/points/lines. Its a little hard to explain but if you make a line invisible then switch graph types you will see what is happening. I think this might be an issue with the scatter plot because that one doesn't show up on mine. The line you disable doesn't show up.

**Comment by jmiller656** [comment]
Yeah this is part of a previous issue, I'm working on it. Getting closer. Should have it fixed by the end of the day

**Comment by jmiller656** [comment]
Hide persistence has been fixed

**Comment by baozi90** [comment]
The graph still does't show up for scatter.

Below is what the graph looks like as well as the error I got when I go to the scatter after disabled a newly added row of data in the bar graph:

![screen shot 2015-06-25 at 13 37 28](https://cloud.githubusercontent.com/assets/11864006/8361186/94950832-1b3f-11e5-9b19-8ecc94fcdc7a.png)


![screen shot 2015-06-25 at 13 37 03](https://cloud.githubusercontent.com/assets/11864006/8361190/9a25aa72-1b3f-11e5-900c-76864f98df87.png)

**Comment by baozi90** [comment]
The graph still does't show up for scatter.

Below is what the graph looks like as well as the error I got when I go to the scatter after disabled a newly added row of data in the bar graph:

![screen shot 2015-06-25 at 13 37 28](https://cloud.githubusercontent.com/assets/11864006/8361186/94950832-1b3f-11e5-9b19-8ecc94fcdc7a.png)


![screen shot 2015-06-25 at 13 37 03](https://cloud.githubusercontent.com/assets/11864006/8361190/9a25aa72-1b3f-11e5-900c-76864f98df87.png)

**Comment by jmiller656** [comment]
Fixed scatterplot error. Need to work on making scatterplot only circles

**Comment by baozi90** [comment]
The scatterplot works now. (The graph isn't blank anymore.) 

Also, while changing to another graph type with the row unchecked, it doesn't show up, at first, on the next graph when enabled. 

This is the error I've got while doing that:

[Error] TypeError: undefined is not an object (evaluating 'chart.datasets[row-1].points[col - 1]')
	(anonymous function) (slickTable.js, line 107)
	notify (slick.core.js, line 126)
	trigger (slick.grid.js, line 1015)
	execute (slick.grid.js, line 3185)
	commitCurrentEdit (slick.grid.js, line 3206)
	commitCurrentEdit (slick.core.js, line 451)
	handleClick (slick.grid.js, line 2291)
	dispatch (jquery-1.11.2.js, line 4665)
	dispatch (jquery.event.drag-2.2.js, line 374)
	handle (jquery-1.11.2.js, line 4333)

**Comment by smcintosh881** [comment]
I noticed this morning the scatter plot does not allow line color change. Is this a feature or a bug?
If you try to change the color for scatter nothing happens, then if you change to bar or line the color shows up, then if you change back to scatter the color will still be there. It just doesn't change color initially.
