### ISSUE TITLE
Downloading Graph

### ISSUE THREAD

**Issue by smcintosh881** [RITAccess/data-analyzer#69]
When you download the CSV file it will download the wrong file. No matter what your graph contains it will always download the same graph. This happens on multiple computers.

**Comment by baozi90** [comment]
This a screenshot of what we got when downloading any table data:

![screen shot 2015-06-25 at 15 35 42](https://cloud.githubusercontent.com/assets/11864006/8363877/0cb1a8f6-1b50-11e5-929f-92aa4f3fcae6.png)

**Comment by jmiller656** [comment]
This is not a problem with the PHP, but with permissions on the local server that you are using. I replicated the problem on my server and without changing any code, fixed it by restoring the correct permissions to the local server

**Comment by baozi90** [comment]
Oh okay, I changed the permission and it worked. Do I need to change it every time I pull or anything like that?

**Comment by baozi90** [comment]
Oh okay, I changed the permission and it worked. Do I need to change it every time I pull or anything like that?

**Comment by jmiller656** [comment]
I'm not sure, it depends on how your server works I think.
