### ISSUE TITLE
Placement of Buttons Under the Table

### ISSUE THREAD

**Issue by baozi90** [RITAccess/data-analyzer#72]
Need to modify the placement of the buttons under the table as more buttons are now added.

**Comment by smcintosh881** [comment]
For the undo button we could make it the undo symbol with aria-label="Undo". That way if we decide to add a redo option we can put the redo symbol next to the undo symbol

**Comment by baozi90** [comment]
- Replaced the word "Undo" with the undo icon.
- aria-label="Undo" is used.
- Separated the Download CSV, Undo, and Print buttons from the add/subtract row/column buttons, so the buttons won't as easily overlap when on smaller screen size, especially if more buttons are to be added.
