### ISSUE TITLE
Clean up the UI

### ISSUE THREAD

**Issue by Rek3650** [RITAccess/data-analyzer#74]
Now that we have even more buttons and options we should look into reordering elements to keep a clean and usable design. The header is now two rows large making it a bit cumbersome. 
![screen shot 2015-06-29 at 3 23 18 pm](https://cloud.githubusercontent.com/assets/1157962/8416313/e3b88c46-1e72-11e5-82c9-107ba6c57a7a.png)
Dr. Ludi liked the idea of moving the audio controls down closer to the table itself so that relevant data like the table were closer to the audio options. Here is just a quick example of how it could be arranged. 
![screen shot 2015-06-29 at 3 27 08 pm](https://cloud.githubusercontent.com/assets/1157962/8416376/67bf6bae-1e73-11e5-893c-2d3e583556d1.png)
It could be above or below the table but it no longer seems logical to keep it in the header of the page. 
I also think we can condense the graph type radio buttons into the new free space in the header. They could either stay as radio buttons or be changed to a dropdown menu. This way the header is delighted to graph management.
![screen shot 2015-06-29 at 3 30 41 pm](https://cloud.githubusercontent.com/assets/1157962/8416440/d4803106-1e73-11e5-9807-b1c73954fb26.png)

**Comment by baozi90** [comment]
How about something like this for the audio controls:

![screen shot 2015-06-29 at 16 39 29](https://cloud.githubusercontent.com/assets/11864006/8417893/714c11fe-1e7d-11e5-83a8-163dd084632d.png)

**Comment by Rek3650** [comment]
I like it :+1:

**Comment by baozi90** [comment]
Just in case it's needed, here's the code for the radio chart type select:

**Comment by baozi90** [comment]
Summary:

- audio controls are below the graph
- radio chart type select is now option select, in the header, and functioning
