### ISSUE TITLE
Add unique audio controls for the bar graph

### ISSUE THREAD

**Issue by Rek3650** [RITAccess/data-analyzer#75]
Currently the bar graph is treated exactly the same as the line graph and scatter plot. The audio data for the bar graph should be represented differently considering the fact that a bar graph will generally be used to display a fundamentally different type of data than a line graph. To achieve this we should implement a unique set of controls for the bar graph. 

This new set of controls should allow the user to:
1. Choose between playing 1 row across all columns (similar to its current functionality)
2. Play based on column. e.g. play all data from the month of march. 
3. Possibly have the ability to play across the entire graph using columns as chords.

**Comment by jmiller656** [comment]
Ok, so I have each of these working. The only one that seems to be a problem is using chords. It works, but it sounds like a cat jumping around on a piano and I'm not quite sure that's what we're looking for. About to start adding buttons for this now.
