### ISSUE TITLE
Which One Looks Better?

### ISSUE THREAD

**Issue by baozi90** [RITAccess/data-analyzer#76]
To the left:

![screen shot 2015-06-29 at 18 29 47](https://cloud.githubusercontent.com/assets/11864006/8420073/0d36b6a0-1e8d-11e5-8c61-a538f66bf251.png)

In the middle:

![screen shot 2015-06-29 at 18 30 00](https://cloud.githubusercontent.com/assets/11864006/8420080/1b1599bc-1e8d-11e5-9583-c7ad9f34b8de.png)

Here's another one for right:

![screen shot 2015-06-30 at 08 53 48](https://cloud.githubusercontent.com/assets/11864006/8431171/ae51a266-1f05-11e5-864e-4f79be7048c3.png)

**Comment by smcintosh881** [comment]
![screen shot 2015-06-30 at 8 52 13 am](https://cloud.githubusercontent.com/assets/9065471/8431127/547c174e-1f05-11e5-9a4e-f6dab71967b7.png)

This is what the right would look like

**Comment by baozi90** [comment]
Here's another one for right:

![screen shot 2015-06-30 at 08 53 48](https://cloud.githubusercontent.com/assets/11864006/8431156/9a4e26cc-1f05-11e5-8398-a3f5a9e6d13d.png)

**Comment by baozi90** [comment]
I've pushed the right one for now because that's the one with the most codes needed so far.
