### ISSUE TITLE
Scatter Plot Row Data Doesn't Show Up

### ISSUE THREAD

**Issue by baozi90** [RITAccess/data-analyzer#77]
So far, this only applies to scatter plot:

- When changing the color of a row, while it's disabled (unchecked), the color doesn't change as other graphs would and should. 
- After the last step, I changed the data of the corresponding row.
- Then enable (check) the row with the color and data changed: 

** the color doesn't change in the summary box and the corresponding row data doesn't show up on the scatter plot.

Here's some screenshots along with the errors I got:

(Changing Color)
![screen shot 2015-06-30 at 10 57 08](https://cloud.githubusercontent.com/assets/11864006/8434111/7ca05886-1f17-11e5-8e24-2eab26cd9c77.png)

(Changing Data)
![screen shot 2015-06-30 at 10 57 36](https://cloud.githubusercontent.com/assets/11864006/8434113/805ed4b6-1f17-11e5-904e-9fc7bd8a69e7.png)

(Enable/Check Row)
![screen shot 2015-06-30 at 10 57 46](https://cloud.githubusercontent.com/assets/11864006/8434115/87d7a970-1f17-11e5-9b80-5fef99580984.png)

**Comment by jmiller656** [comment]
Should be working again now. An old typo somehow made its way back into the code.

**Comment by baozi90** [comment]
Yup, I think it does now. (Was trying to delete the issue but guess it's not a feature yet..)
