### ISSUE TITLE
Issue when first loading CSV

### ISSUE THREAD

**Issue by smcintosh881** [RITAccess/data-analyzer#81]
Sometimes when I go to load a CSV and press Open, nothing happens. The console prints this. Does anyone else get this error?

![screen shot 2015-07-01 at 7 52 52 am](https://cloud.githubusercontent.com/assets/9065471/8453852/764e9420-1fc6-11e5-85c7-64a81d38cfd9.png)

**Comment by smcintosh881** [comment]
![screen shot 2015-07-01 at 8 15 56 am](https://cloud.githubusercontent.com/assets/9065471/8454176/6dd04282-1fc9-11e5-9726-3b57bc30e195.png)

**Comment by jmiller656** [comment]
I've gotten it a couple times. Not sure what is causing it.

**Comment by melissay94** [comment]
Same, refreshing the page makes it go away but it always comes back. My guess would be that something is loading before something else it needs in order to work properly.

**Comment by smcintosh881** [comment]
I am no longer getting this error. Is anyone else?

**Comment by baozi90** [comment]
Nope, I don't see it on Chrome, Firefox, and Safari. I do sometimes get the file listener error (not sure if that's the right name).

**Comment by smcintosh881** [comment]
I haven't gotten that one before. I think this issue can be closed

**Comment by Rek3650** [comment]
I think I managed to fix this. Since its virtually impossible to replicate I am going to close this issue for now. If it arises again we can re-open it.
