### ISSUE TITLE
CSS Thoughts

### ISSUE THREAD

**Issue by smcintosh881** [RITAccess/data-analyzer#83]
Thoughts on this for the css layout?
![screen shot 2015-07-01 at 10 25 44 am](https://cloud.githubusercontent.com/assets/9065471/8456782/93c390e0-1fdb-11e5-93e2-86f5acd44c63.png)

**Comment by baozi90** [comment]
Looks good. How about combining the Graph Data sections too?

**Comment by smcintosh881** [comment]
one large continues box?

**Comment by baozi90** [comment]
Yup, maybe excluding the graph for now..

**Comment by smcintosh881** [comment]
![screen shot 2015-07-01 at 10 57 11 am](https://cloud.githubusercontent.com/assets/9065471/8457539/f3b32110-1fdf-11e5-832f-bb715389a9e1.png)
