### ISSUE TITLE
Refresh/reset table

### ISSUE THREAD

**Issue by smcintosh881** [RITAccess/data-analyzer#85]
What are the thoughts on possibly adding a refresh/reset button under the table that when pressed restores the table to the original state. This is useful if a user makes several changes (50) to the data but decides they want the original back (using the undo button would take forever). The location of another button would be down next to the undo/redo/download/print buttons using the refresh symbol.

![screen shot 2015-06-29 at 11 22 11 am](https://cloud.githubusercontent.com/assets/9065471/8458622/1e538576-1fe6-11e5-9fa3-3a31985ee0ad.png)

(could be placed in any order amongst those buttons)

**Comment by smcintosh881** [comment]
Make sure that the refresh buttons are labeled for what section of the page they will be refreshing

**Comment by melissay94** [comment]
Reset button for table fully functional and not reversible
