### ISSUE TITLE
Change Text Color

### ISSUE THREAD

**Issue by baozi90** [RITAccess/data-analyzer#86]
Since we have a feature to change the background color for the entire site and the graph, the feature for changing the corresponding text colors could be added.

This feature will most likely be placed somewhere in/near the Change Background Color section as well.

**Comment by jmiller656** [comment]
What might work well is adding this somewhere inside the function to change background color and doing some math to get a color that will contrast with the new background color.

**Comment by jmiller656** [comment]
Found a good contrast algorithm: http://www.w3.org/TR/WCAG20-TECHS/G17.html
I'll be working with that to get a suitable text color.
