### ISSUE TITLE
Scatter Plot Clutters

### ISSUE THREAD

**Issue by baozi90** [RITAccess/data-analyzer#95]
Data shown on scatter plot all clutters on the zero y axis:

<img width="283" alt="screen shot 2015-07-06 at 11 24 31" src="https://cloud.githubusercontent.com/assets/11864006/8525971/c8a0ed36-23d1-11e5-864c-081cc9f269b2.png">

Is this already a problem and/or does it only shows up on my browsers?

**Comment by erl7902** [comment]
whoops, I was testing something on friday and completely forgot I did that.
Sorry, I'll fix that asap

**Comment by baozi90** [comment]
It's alright.

**Comment by erl7902** [comment]
Should be fixed

**Comment by baozi90** [comment]
Yup, it looks normal now.
